name: Sync to Hugging Face hub
on:
  push:
    branches: [ main ]  # Change this to your default branch if different

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for complete history
          lfs: true

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          
          # Configure Hugging Face repository
          git remote add hub git@hf.co:kernels-community/mrope_get_position_ids
          
          # Fetch from Hugging Face to ensure we have the latest state
          git fetch hub || true
          
          # Push to Hugging Face, preserving history
          # The '+' before the ref forces the update only if necessary while preserving history
          git push https://$HF_TOKEN@huggingface.co/kernels-community/mrope_get_position_ids +main:main