name: Sync to Hugging Face hub
on:
  push:
    branches: [ main ]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Install huggingface-cli
        run: pip install huggingface_hub

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Login to Hugging Face and add git credentials
          huggingface-cli login --token $HF_TOKEN --add-to-git-credential
          
          # Configure git
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          
          # Add remote and push
          git remote add hub "https://huggingface.co/kernels-community/mrope_get_position_ids.git"
          git push hub main