name: Sync to Hugging Face hub
on:
  push:
    branches: [ main ]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          
          # Configure Hugging Face repository using HTTPS
          git remote add hub https://huggingface.co/kernels-community/mrope_get_position_ids
          
          # Fetch from Hugging Face
          git fetch hub || true
          
          # Push to Hugging Face using HTTPS with token
          git push https://$HF_TOKEN@huggingface.co/kernels-community/mrope_get_position_ids +main:main